homepage:
    path:   /
    defaults: { _controller: AppBundle:JokePost:list }

jokepost:
    path:   /jokepost/new
    defaults: { _controller: AppBundle:JokePost:new }

jokepost-list:
    path:   /jokepost/list
    defaults: { _controller: AppBundle:JokePost:list }

jokepost-like:
    path:   /jokepost/like/{id}
    defaults: { _controller: AppBundle:JokePost:like }
    requirements:
        id: '\d+'

jokepost-unlike:
    path:   /jokepost/unlike/{id}
    defaults: { _controller: AppBundle:JokePost:unlike }
    requirements:
        id: '\d+'

jokepost-one:
    path:   /jokepost/{id}
    defaults: { _controller: AppBundle:JokePost:one }
    requirements:
        id: '\d+'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user-list:
    path:   /user/list
    defaults: { _controller: AppBundle:User:list }
