homepage:
    path:   /
    defaults: { _controller: AppBundle:Default:index }

api-register:
    path:   /api/register
    defaults: { _controller: AppBundle:User:registerApi }

jokepost:
    path:   /jokepost/new
    defaults: { _controller: AppBundle:JokePost:new }

jokepost-list:
    path:   /jokepost/list
    defaults: { _controller: AppBundle:JokePost:list }
    methods:  [GET]

jokepost-like:
    path:   /jokepost/like/{id}
    defaults: { _controller: AppBundle:JokePost:like }
    requirements:
        id: '\d+'

jokepost-unlike:
    path:   /jokepost/unlike/{id}
    defaults: { _controller: AppBundle:JokePost:unlike }
    requirements:
        id: '\d+'

jokepost-one:
    path:   /jokepost/{id}
    defaults: { _controller: AppBundle:JokePost:one }
    requirements:
        id: '\d+'

api-jokepost-list:
    path:   /api/jokepost/list
    defaults: { _controller: AppBundle:JokePost:listApi }

api-jokepost-like:
    path:   /api/jokepost/like/{id}
    defaults: { _controller: AppBundle:JokePost:likeApi }
    methods:  [POST]
    requirements:
        id: '\d+'

api-jokepost-unlike:
    path:   /jokepost/unlike/{id}
    defaults: { _controller: AppBundle:JokePost:unlikeApi }
    methods:  [POST]
    requirements:
        id: '\d+'

user-list:
    path:   /user/list
    defaults: { _controller: AppBundle:User:list }
    methods:  [GET]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
