homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

jokepost:
    path:     /jokepost/add
    defaults: { _controller: AppBundle:JokePost:new }

jokepost-list:
    path:     /jokepost/list
    defaults: { _controller: AppBundle:JokePost:list }

jokepost-one:
    path:     /jokepost/{id}
    defaults: { _controller: AppBundle:JokePost:one }
    requirements:
        id: '\d+'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user-list:
    path:     /user/list
    defaults: { _controller: AppBundle:User:list }  