homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

jokepost:
    path:     /jokepost
    defaults: { _controller: AppBundle:JokePost:new }

jokepost-list:
    path:     /jokepost/list
    defaults: { _controller: AppBundle:JokePost:list }