homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

jokepost:
    path:     /jokepost
    defaults: { _controller: AppBundle:JokePost:new }

jokepost-list:
    path:     /jokepost/list
    defaults: { _controller: AppBundle:JokePost:list }

jokepost-one:
    path:     /jokepost/{id}
    defaults: { _controller: AppBundle:JokePost:one }

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }  

user-list:
    path:     /user/list
    defaults: { _controller: AppBundle:User:list }  