AppBundle\Entity\JokePost:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\JokePostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        upvotes:
            type: integer
        downvotes:
            type: integer
        img:
            type: string
            length: 255
        date:
            type: datetime
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: jokepost
    lifecycleCallbacks: {  }
