AppBundle\Entity\Vote:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        choice:
            type: integer
    lifecycleCallbacks: {  }
